[package]
name = "naga"
version = "0.1.0"
authors = ["Dzmitry Malyshau <kvarkus@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1"
fxhash = "0.2"
log = "0.4"
spirv_headers = "1"

[dev-dependencies]
env_logger = "0.6"
